version: "2"

run:
  go: "1.26"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec
    - bodyclose
  settings:
    gosec:
      excludes:
        - G104
        - G115
        - G117
        - G204
        - G304
        - G702
        - G402
        - G704
        - G705
        - G706
  exclusions:
    paths:
      - ui/dist
